# Generated by Django 5.1.6 on 2025-02-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
